# Generated by Django 4.0.3 on 2022-03-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_description_category_paginated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='blog/post_detail.html', max_length=500, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='Статья'),
        ),
    ]
