# Generated by Django 4.0.3 on 2022-04-01 18:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Для зарегестрированых?')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать?')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя латиница')),
                ('title', models.CharField(max_length=100, verbose_name='Имя русский')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Для зарегестрированых?')),
                ('anchor', models.CharField(max_length=100, verbose_name='Якорь')),
                ('url', models.SlugField(max_length=100, verbose_name='url')),
                ('active', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitems', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'ПодМеню',
                'verbose_name_plural': 'ПодМеню',
            },
        ),
    ]
